name: guptik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.10.7 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.10.2
  mobile_scanner: ^7.1.4
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  http: ^1.1.0
  app_links: ^6.3.2
  go_router: ^17.0.1
  crypto: ^3.0.3
  font_awesome_flutter: ^10.6.0
  http_parser: ^4.0.2
  file_picker: ^10.3.10  # âœ… Fixed version
  audioplayers: ^5.2.1
  path_provider: ^2.1.3 
  device_info_plus: ^12.3.0 
  record: ^6.2.0
  video_player: ^2.5.1
  url_launcher: ^6.1.7
  # State Management
  provider: ^6.1.2
  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  # Utilities
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  intl: ^0.19.0
  # Location & Wifi
  geolocator: ^10.1.0
  wifi_scan: ^0.4.0+2
  photo_manager: ^3.0.0
  transparent_image: ^2.0.0
  share_plus: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/MetaFly.png"